version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 moviebackend.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=moviebackend.settings
    restart: always
