version: '3.8'

services:
  web:
    build: .
    container_name: django_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=52.91.196.218
      - DJANGO_SETTINGS_MODULE=moviebackend.settings  # <-- Add this line

