name: Deploy Django App to EC2

on:
  push:
    branches:
      - master  # Change this to your branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.52.91.196.218 }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@${{ secrets.52.91.196.218 }} << 'EOF'
            cd /home/ubuntu/your-project-folder
            git pull origin master
            docker-compose down
            docker-compose up --build -d
            sudo systemctl restart nginx
          EOF
